name = "gsoc-contributors"
subteam-of = "launching-pad"
kind = "marker-team"

[people]
leads = []
members = [
    "Sa4dUs",
    "lapla-cogito",
    "Shourya742",
    "sgasho",
    "moabo3li",
    "CoCo-Japan-pan",
    "NONnonHere",
    "dybucc",
    "vishruth-thimmaiah",
    "xonx4l",
    "zedddie",
    "Walnut356",
    "Cloud0310"
]
alumni = [
    "d-sonuga",
    "mav3ri3k",
    "s7tya",
    "ding-young",
    "suaviloquence",
    "tiif",
    "shannmu",
    "KMJ-007",
    "Oneirical",
    "FractalFir",
    "dawidl022",
    "namanlp",
    "zjp-CN",
    "GlitchlessCode",
    "madhav-madhusoodanan",
    "Sakib25800",
    "LorrensP-2158466",
    "CLIDragon",
    "FranciscoTGouveia",
    "mbyx",
    "DriedYellowPeach",
    "makai410",
    "Pyr0de",
    "secona",
]

[permissions]
dev-desktop = true
bors.rust.try = true
perf = true

[[roles]]
id = "guest"
description = "External GSoC contributor"

[[zulip-groups]]
name = "gsoc-contributors"

[website]
name = "Rust Google Summer of Code contributors"
description = "Contributors that have participated in Rust GSoC projects"
