name = "perspectives-on-llms-editors"
subteam-of = "launching-pad"

[people]
leads = ["nikomatsakis", "oli-obk", "davidtwco"]
members = ["nikomatsakis", "oli-obk", "davidtwco"]
alumni = []

[[github]]
orgs = ["rust-lang"]

[website]
name = "Perspectives on LLMs editors"
description = "Maintains the perspectives on LLMs repo"
repo = "https://github.com/rust-lang/perspectives-on-llms/"
